### ISSUE TITLE
landing page readme example is outdated

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [antonok-edm/ssd1309#5]
The example is outdated: https://crates.io/crates/ssd1309

**Comment by HerrMuellerluedenscheid** [comment]
I don't know if this is worth mentioning somewhere but I put together an example using the tiva-c-launchpad + SSD1309 via SPI here: https://github.com/HerrMuellerluedenscheid/tm4c-oled-example

Hope that helps others to get started a bit faster than I did :)

**Comment by antonok-edm** [comment]
Closing as per https://github.com/antonok-edm/ssd1309/issues/4#issuecomment-967750112 - I just removed the README example altogether, since it was prone to get outdated anyways.

Also added your repos to the README in https://github.com/antonok-edm/ssd1309/commit/5e815ae28935adbb855bc206746d4a6c0fa04cf6 - thanks!
